<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'slug' => 'weight-care',
                'type' => 'clinical',
                'category' => 'Weight management',
                'category_ar' => 'إدارة الوزن',
                'name' => 'Weight Care Pathway',
                'name_ar' => 'مسار رعاية الوزن',
                'short_description' => 'Assessment, clinician review, care plan and connected follow-up.',
                'short_description_ar' => 'تقييم، مراجعة طبيب، خطة رعاية، ومتابعة متصلة.',
                'long_description' => 'A structured metabolic-care journey that starts with your goals and history. The clinician may recommend lifestyle care, investigations, a consultation, treatment, referral, or no treatment.',
                'long_description_ar' => 'رحلة رعاية أيضية منظّمة تبدأ بأهدافك وتاريخك الصحي. قد يوصي الطبيب برعاية نمط الحياة، أو فحوصات، أو استشارة، أو علاج، أو إحالة، أو عدم الحاجة لعلاج.',
                'price' => 249,
                'due_now' => 149,
                'price_note' => 'AED 149 review fee today · care plan from AED 249/month only if approved',
                'price_note_ar' => 'رسوم مراجعة 149 درهمًا اليوم · خطة الرعاية من 249 درهمًا/شهريًا فقط عند الموافقة',
                'badge' => 'Doctor review required',
                'badge_ar' => 'يتطلب مراجعة طبيب',
                'consult_only' => false,
                'quiz_category' => 'Weight management',
                'includes' => ['Adaptive metabolic assessment', 'Licensed clinician review', 'One video consultation when indicated', 'Care Passport, check-ins and secure messaging'],
                'includes_ar' => ['تقييم أيضي تكيّفي', 'مراجعة طبيب مرخّص', 'استشارة فيديو واحدة عند الحاجة', 'جواز الرعاية، متابعات، ومراسلة آمنة'],
                'flow' => ['Choose goal', 'Complete assessment', 'Clinician decides', 'Accept final plan'],
                'flow_ar' => ['اختر هدفك', 'أكمل التقييم', 'يقرر الطبيب', 'اقبل الخطة النهائية'],
            ],
            [
                'slug' => 'fibre-support',
                'type' => 'direct',
                'category' => 'Appetite + nutrition',
                'category_ar' => 'الشهية والتغذية',
                'name' => 'Daily Fibre + Appetite Support',
                'name_ar' => 'الألياف اليومية ودعم الشهية',
                'short_description' => 'A simple nutrition-support routine with clear ingredients and guidance.',
                'short_description_ar' => 'روتين بسيط لدعم التغذية بمكوّنات واضحة وإرشادات.',
                'long_description' => 'A fictional non-prescription nutrition support product with responsible instructions, ingredient transparency and optional care-team guidance. It is not a substitute for medical assessment.',
                'long_description_ar' => 'منتج دعم غذائي افتراضي لا يتطلب وصفة طبية، بتعليمات مسؤولة وشفافية في المكوّنات وإرشاد اختياري من فريق الرعاية. لا يُعد بديلاً عن التقييم الطبي.',
                'price' => 119,
                'due_now' => 119,
                'price_note' => 'One-time purchase · 30 servings',
                'price_note_ar' => 'شراء لمرة واحدة · 30 حصة',
                'badge' => 'Buy now',
                'badge_ar' => 'اشترِ الآن',
                'consult_only' => false,
                'quiz_category' => null,
                'includes' => ['30-serving sealed jar', 'Ingredient and allergen information', 'Nutrition guide', 'Secure product-support messaging'],
                'includes_ar' => ['عبوة محكمة الغلق 30 حصة', 'معلومات المكوّنات ومسببات الحساسية', 'دليل تغذية', 'مراسلة آمنة لدعم المنتج'],
                'flow' => ['Add to cart', 'Verify account', 'Vendor prepares', 'Discreet delivery'],
                'flow_ar' => ['أضف إلى السلة', 'تحقق من الحساب', 'يجهّز المورّد', 'توصيل سرّي'],
            ],
            [
                'slug' => 'hair-system',
                'type' => 'clinical',
                'category' => 'Hair health',
                'category_ar' => 'صحة الشعر',
                'name' => 'Personalised Hair Health System',
                'name_ar' => 'نظام صحة الشعر الشخصي',
                'short_description' => 'Photo-guided assessment, clinician review and a tailored care system.',
                'short_description_ar' => 'تقييم موجّه بالصور، مراجعة طبيب، ونظام رعاية مخصص.',
                'long_description' => 'A clinician-led pathway for shedding, pattern change and scalp symptoms. The product request never determines the diagnosis or plan; photos, history and investigations may be required.',
                'long_description_ar' => 'مسار يقوده الطبيب لتساقط الشعر وتغيّر النمط وأعراض فروة الرأس. طلب المنتج لا يحدد التشخيص أو الخطة أبدًا؛ قد تُطلب صور وتاريخ صحي وفحوصات.',
                'price' => 289,
                'due_now' => 99,
                'price_note' => 'AED 99 review fee today · products only after approval',
                'price_note_ar' => 'رسوم مراجعة 99 درهمًا اليوم · المنتجات فقط بعد الموافقة',
                'badge' => 'Doctor review required',
                'badge_ar' => 'يتطلب مراجعة طبيب',
                'consult_only' => false,
                'quiz_category' => 'Hair health',
                'includes' => ['Guided image capture', 'Hair and scalp assessment', 'Clinician-selected plan', 'Progress photography and follow-up'],
                'includes_ar' => ['التقاط صور موجّه', 'تقييم الشعر وفروة الرأس', 'خطة يختارها الطبيب', 'تصوير التقدم والمتابعة'],
                'flow' => ['Share history', 'Upload photos', 'Clinician review', 'Plan + fulfilment'],
                'flow_ar' => ['شارك التاريخ الصحي', 'ارفع الصور', 'مراجعة الطبيب', 'الخطة والتنفيذ'],
            ],
            [
                'slug' => 'skin-routine',
                'type' => 'direct',
                'category' => 'Skin',
                'category_ar' => 'البشرة',
                'name' => 'Sensitive Skin Clarity Routine',
                'name_ar' => 'روتين وضوح البشرة الحساسة',
                'short_description' => 'A gentle fictional cleanser, serum and moisturiser system.',
                'short_description_ar' => 'نظام لطيف افتراضي من منظف وسيروم ومرطب.',
                'long_description' => 'A direct-care routine for patients who want a simple, fragrance-conscious starting point. Persistent, severe, painful or rapidly changing symptoms should enter the clinician review pathway.',
                'long_description_ar' => 'روتين رعاية مباشرة للمرضى الراغبين في بداية بسيطة خالية من العطور القوية. الأعراض المستمرة أو الشديدة أو المؤلمة أو سريعة التغيّر يجب أن تدخل مسار مراجعة الطبيب.',
                'price' => 159,
                'due_now' => 159,
                'price_note' => 'One-time purchase · three-piece routine',
                'price_note_ar' => 'شراء لمرة واحدة · روتين من ثلاث قطع',
                'badge' => 'Buy now',
                'badge_ar' => 'اشترِ الآن',
                'consult_only' => false,
                'quiz_category' => null,
                'includes' => ['Gentle cleanser', 'Barrier-support serum', 'Daily moisturiser', 'Patch-test and escalation guidance'],
                'includes_ar' => ['منظف لطيف', 'سيروم داعم لحاجز البشرة', 'مرطب يومي', 'إرشادات اختبار الحساسية والتصعيد'],
                'flow' => ['Review details', 'Add to cart', 'Vendor prepares', 'Track delivery'],
                'flow_ar' => ['راجع التفاصيل', 'أضف إلى السلة', 'يجهّز المورّد', 'تتبّع التوصيل'],
            ],
            [
                'slug' => 'home-lab',
                'type' => 'service',
                'category' => 'Diagnostics',
                'category_ar' => 'الفحوصات التشخيصية',
                'name' => 'Home Metabolic Lab Panel',
                'name_ar' => 'لوحة الفحوصات الأيضية المنزلية',
                'short_description' => 'Licensed home collection with results routed to your clinician.',
                'short_description_ar' => 'جمع عينات منزلي مرخّص مع توجيه النتائج إلى طبيبك.',
                'long_description' => 'A fictional home diagnostic service covering a clinician-approved metabolic baseline. Exact tests, preparation, eligibility and interpretation are confirmed before collection.',
                'long_description_ar' => 'خدمة فحص تشخيصي منزلي افتراضية تغطي خط أساس أيضي معتمد من الطبيب. تُؤكَّد الفحوصات الدقيقة والتحضير والأهلية والتفسير قبل الجمع.',
                'price' => 449,
                'due_now' => 449,
                'price_note' => 'Includes home collection in Dubai',
                'price_note_ar' => 'يشمل الجمع المنزلي في دبي',
                'badge' => 'Home service',
                'badge_ar' => 'خدمة منزلية',
                'consult_only' => false,
                'quiz_category' => null,
                'includes' => ['Home collection appointment', 'Identity and order verification', 'Chain of custody', 'Results in your Care Passport'],
                'includes_ar' => ['موعد جمع منزلي', 'التحقق من الهوية والطلب', 'سلسلة حفظ العينة', 'النتائج في جواز الرعاية الخاص بك'],
                'flow' => ['Choose slot', 'Order verified', 'Home collection', 'Clinician reviews'],
                'flow_ar' => ['اختر موعدًا', 'التحقق من الطلب', 'الجمع المنزلي', 'يراجع الطبيب'],
            ],
            [
                'slug' => 'intimate-review',
                'type' => 'clinical',
                'category' => 'Sexual health',
                'category_ar' => 'الصحة الجنسية',
                'name' => 'Private Sexual Health Review',
                'name_ar' => 'مراجعة الصحة الجنسية الخاصة',
                'short_description' => 'Discreet assessment with cardiovascular and medicine-safety checks.',
                'short_description_ar' => 'تقييم سرّي مع فحوصات سلامة القلب والأوعية الدموية والأدوية.',
                'long_description' => 'A confidential clinician review for common sexual-health concerns. Urgent symptoms, cardiovascular risk or medicine interactions stop the commercial pathway and prompt the appropriate next step.',
                'long_description_ar' => 'مراجعة سرّية من طبيب لمخاوف الصحة الجنسية الشائعة. الأعراض العاجلة أو مخاطر القلب والأوعية الدموية أو تفاعلات الأدوية توقف المسار التجاري وتوجّه إلى الخطوة التالية المناسبة.',
                'price' => 199,
                'due_now' => 120,
                'price_note' => 'AED 120 clinical review fee today',
                'price_note_ar' => 'رسوم مراجعة سريرية 120 درهمًا اليوم',
                'badge' => 'Doctor review required',
                'badge_ar' => 'يتطلب مراجعة طبيب',
                'consult_only' => false,
                'quiz_category' => 'Sexual health',
                'includes' => ['Private adaptive assessment', 'Licensed clinician review', 'Secure follow-up questions', 'Consultation or referral when indicated'],
                'includes_ar' => ['تقييم تكيّفي خاص', 'مراجعة طبيب مرخّص', 'أسئلة متابعة آمنة', 'استشارة أو إحالة عند الحاجة'],
                'flow' => ['Private intake', 'Safety screen', 'Clinician decides', 'Next step'],
                'flow_ar' => ['استقبال خاص', 'فحص السلامة', 'يقرر الطبيب', 'الخطوة التالية'],
            ],
            [
                'slug' => 'advanced-consult',
                'type' => 'service',
                'category' => 'Advanced wellness',
                'category_ar' => 'العافية المتقدمة',
                'name' => 'Advanced Wellness Consultation',
                'name_ar' => 'استشارة العافية المتقدمة',
                'short_description' => 'Consultation first for peptide, recovery and healthy-aging enquiries.',
                'short_description_ar' => 'استشارة أولًا لاستفسارات الببتيدات والتعافي والشيخوخة الصحية.',
                'long_description' => 'A clinician consultation for patients seeking to understand advanced wellness options. No therapy is promised, named or added to the cart; the clinician evaluates goals, evidence, risks and alternatives.',
                'long_description_ar' => 'استشارة طبية للمرضى الراغبين في فهم خيارات العافية المتقدمة. لا يُوعد بأي علاج أو يُسمّى أو يُضاف إلى السلة؛ يُقيّم الطبيب الأهداف والأدلة والمخاطر والبدائل.',
                'price' => 350,
                'due_now' => 350,
                'price_note' => '45-minute consultation · no product included',
                'price_note_ar' => 'استشارة 45 دقيقة · لا يشمل أي منتج',
                'badge' => 'Consultation only',
                'badge_ar' => 'استشارة فقط',
                'consult_only' => true,
                'quiz_category' => 'Advanced wellness',
                'includes' => ['45-minute qualified clinician visit', 'Pre-visit medical history', 'Evidence and risk discussion', 'Documented advice and next steps'],
                'includes_ar' => ['زيارة 45 دقيقة مع طبيب مؤهل', 'التاريخ الصحي قبل الزيارة', 'مناقشة الأدلة والمخاطر', 'نصيحة موثّقة وخطوات تالية'],
                'flow' => ['Book visit', 'Share history', 'Clinician consult', 'Advice or referral'],
                'flow_ar' => ['احجز الزيارة', 'شارك التاريخ الصحي', 'استشارة الطبيب', 'نصيحة أو إحالة'],
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
